"""Opt-in fused grasp-mode head for LeRobot PI0.5.

The head is trained jointly with PI0.5 and consumes pooled visual-language
prefix embeddings. Continuous residuals remain generated by the native flow
action expert. This keeps grasp-family selection inside the VLA while avoiding
the instability of encoding a categorical decision in a diffusion trajectory.
"""

from __future__ import annotations

from collections.abc import Mapping
from typing import Any

from .pi05_state_token_adapter import pi05_state_token_context


PI05_MODE_HEAD_MODULE = "mode_head"
PI05_MODE_HEAD_POOLING_MASKED_MEAN = "masked_mean"
PI05_MODE_HEAD_POOLING_LAST_LANGUAGE_TOKEN = "last_language_token"
PI05_MODE_HEAD_PROTOCOLS = {
    PI05_MODE_HEAD_POOLING_MASKED_MEAN: "parcel-pi05-contextualized-mode-head-v2",
    PI05_MODE_HEAD_POOLING_LAST_LANGUAGE_TOKEN: (
        "parcel-pi05-last-language-token-mode-head-v3"
    ),
}
PI05_MODE_HEAD_PROTOCOL = PI05_MODE_HEAD_PROTOCOLS[
    PI05_MODE_HEAD_POOLING_MASKED_MEAN
]


def normalize_pi05_mode_head_pooling(value: str | None) -> str:
    pooling = str(value or PI05_MODE_HEAD_POOLING_MASKED_MEAN).strip().lower()
    if pooling not in PI05_MODE_HEAD_PROTOCOLS:
        raise ValueError(
            "unsupported PI0.5 mode-head pooling: "
            f"{pooling!r}; expected one of {sorted(PI05_MODE_HEAD_PROTOCOLS)}"
        )
    return pooling


def pi05_mode_head_protocol(pooling: str | None = None) -> str:
    return PI05_MODE_HEAD_PROTOCOLS[normalize_pi05_mode_head_pooling(pooling)]


def pi05_mode_head_pooling_from_protocol(protocol: str) -> str:
    matches = [
        pooling
        for pooling, candidate in PI05_MODE_HEAD_PROTOCOLS.items()
        if candidate == protocol
    ]
    if len(matches) != 1:
        raise ValueError(f"unsupported PI0.5 mode-head protocol: {protocol!r}")
    return matches[0]


def pool_pi05_contextualized_prefix(
    contextualized: Any,
    prefix_pad_masks: Any,
    language_masks: Any,
    *,
    state_token_present: bool,
    pooling: str,
) -> Any:
    """Pool PI0.5 prefix features under a checkpoint-bound protocol."""

    import torch

    pooling = normalize_pi05_mode_head_pooling(pooling)
    if contextualized.ndim != 3 or prefix_pad_masks.shape != contextualized.shape[:2]:
        raise ValueError("PI0.5 contextualized prefix/mask shape mismatch")
    if pooling == PI05_MODE_HEAD_POOLING_MASKED_MEAN:
        valid = prefix_pad_masks.to(dtype=contextualized.dtype).unsqueeze(-1)
        return (contextualized * valid).sum(dim=1) / valid.sum(dim=1).clamp_min(1.0)

    if language_masks.ndim != 2 or language_masks.shape[0] != contextualized.shape[0]:
        raise ValueError("PI0.5 language mask must have shape BxL")
    language_width = int(language_masks.shape[1])
    state_width = 1 if state_token_present else 0
    language_start = int(contextualized.shape[1]) - language_width - state_width
    if language_start < 0:
        raise ValueError("PI0.5 prefix is shorter than its language/state suffix")
    valid_language = language_masks.to(device=contextualized.device, dtype=torch.bool)
    if not valid_language.any(dim=1).all():
        raise ValueError("PI0.5 last-language-token pooling requires a valid token")
    token_positions = torch.arange(
        language_width, device=contextualized.device, dtype=torch.long
    ).unsqueeze(0)
    last_language = token_positions.masked_fill(~valid_language, -1).amax(dim=1)
    gather_index = language_start + last_language
    batch_index = torch.arange(contextualized.shape[0], device=contextualized.device)
    return contextualized[batch_index, gather_index]


def checkpoint_uses_pi05_mode_head(peft_config: Any) -> bool:
    """Detect a checkpoint that fully saves the fused categorical head."""

    modules = (
        peft_config.get("modules_to_save")
        if isinstance(peft_config, Mapping)
        else getattr(peft_config, "modules_to_save", None)
    )
    return bool(modules and PI05_MODE_HEAD_MODULE in set(modules))


def configure_pi05_mode_head_peft_defaults(
    defaults: dict[str, Any],
) -> dict[str, Any]:
    """Persist the randomly initialized head fully in every PEFT checkpoint."""

    result = dict(defaults)
    modules_to_save = list(result.get("modules_to_save") or ())
    if PI05_MODE_HEAD_MODULE not in modules_to_save:
        modules_to_save.append(PI05_MODE_HEAD_MODULE)
    result["modules_to_save"] = modules_to_save
    return result


def pi05_mode_head_logits(
    model: Any,
    images: Any,
    image_masks: Any,
    tokens: Any,
    masks: Any,
    state: Any | None = None,
) -> Any:
    """Predict grasp mode from contextualized PI0.5 visual-language features."""

    import torch
    from lerobot.policies.pi05.modeling_pi05 import (
        make_att_2d_masks,
        prepare_attention_masks_4d,
    )

    if not hasattr(model, PI05_MODE_HEAD_MODULE):
        raise RuntimeError("PI0.5 checkpoint does not contain a fused mode head")
    with pi05_state_token_context(model, state):
        prefix, pad_masks, att_masks = model.embed_prefix(
            images, image_masks, tokens, masks
        )
    attention_dtype = (
        model.paligemma_with_expert.paligemma.model.language_model.layers[0]
        .self_attn.q_proj.weight.dtype
    )
    if attention_dtype == torch.bfloat16:
        prefix = prefix.to(dtype=attention_dtype)
    attention_2d = make_att_2d_masks(pad_masks, att_masks)
    positions = torch.cumsum(pad_masks, dim=1) - 1
    attention_4d = prepare_attention_masks_4d(attention_2d)
    model.paligemma_with_expert.paligemma.model.language_model.config._attn_implementation = (
        "eager"
    )
    (contextualized, _), _ = model.paligemma_with_expert.forward(
        attention_mask=attention_4d,
        position_ids=positions,
        past_key_values=None,
        inputs_embeds=[prefix, None],
        use_cache=False,
    )
    if contextualized is None:
        raise RuntimeError("PI0.5 did not return contextualized prefix features")
    pooled = pool_pi05_contextualized_prefix(
        contextualized,
        pad_masks,
        masks,
        state_token_present=bool(state is not None and hasattr(model, "state_proj")),
        pooling=getattr(
            model, "_parcel_mode_head_pooling", PI05_MODE_HEAD_POOLING_MASKED_MEAN
        ),
    )
    head = getattr(model, PI05_MODE_HEAD_MODULE)
    logits = head(pooled.to(device=next(head.parameters()).device, dtype=torch.float32))
    return logits.float()


def _unwrap_pi05_policy(policy: Any) -> Any:
    candidate = policy
    get_base_model = getattr(candidate, "get_base_model", None)
    if callable(get_base_model):
        candidate = get_base_model()
    if not hasattr(candidate, "_preprocess_images") or not hasattr(candidate, "model"):
        raise RuntimeError("unable to unwrap PI0.5 policy for fused mode inference")
    return candidate


def predict_pi05_mode_head(policy: Any, batch: dict[str, Any]) -> Any:
    """Run the fused head on a preprocessed LeRobot PI0.5 batch."""

    from lerobot.policies.pi05.modeling_pi05 import (
        OBS_LANGUAGE_ATTENTION_MASK,
        OBS_LANGUAGE_TOKENS,
    )

    base_policy = _unwrap_pi05_policy(policy)
    images, image_masks = base_policy._preprocess_images(batch)
    return pi05_mode_head_logits(
        base_policy.model,
        images,
        image_masks,
        batch[OBS_LANGUAGE_TOKENS],
        batch[OBS_LANGUAGE_ATTENTION_MASK],
        batch.get("observation.state"),
    )


def install_pi05_mode_head_adapter(
    *,
    hidden_dim: int = 128,
    pooling: str = PI05_MODE_HEAD_POOLING_MASKED_MEAN,
) -> None:
    """Patch LeRobot PI0.5 with an opt-in visual-language mode head."""

    import torch
    from lerobot.policies.pi05.modeling_pi05 import PI05Policy, PI05Pytorch

    pooling = normalize_pi05_mode_head_pooling(pooling)
    if getattr(PI05Pytorch, "_parcel_mode_head_installed", False):
        installed_pooling = getattr(
            PI05Pytorch, "_parcel_mode_head_pooling", PI05_MODE_HEAD_POOLING_MASKED_MEAN
        )
        if installed_pooling != pooling:
            raise RuntimeError(
                "PI0.5 mode-head adapter is already installed with pooling "
                f"{installed_pooling!r}, not {pooling!r}"
            )
        return
    if hidden_dim <= 0:
        raise ValueError("PI0.5 mode-head hidden dimension must be positive")

    original_model_init = PI05Pytorch.__init__
    original_fix_state_dict = PI05Policy._fix_pytorch_state_dict_keys
    original_peft_defaults = PI05Policy._get_default_peft_targets

    def model_init(self: Any, *args: Any, **kwargs: Any) -> None:
        original_model_init(self, *args, **kwargs)
        embedding = (
            self.paligemma_with_expert.paligemma.model.language_model.embed_tokens
        )
        prefix_width = int(embedding.weight.shape[1])
        self._parcel_mode_head_pooling = pooling
        self.mode_head = torch.nn.Sequential(
            torch.nn.LayerNorm(prefix_width, dtype=torch.float32),
            torch.nn.Linear(prefix_width, hidden_dim, dtype=torch.float32),
            torch.nn.GELU(),
            torch.nn.Linear(hidden_dim, 3, dtype=torch.float32),
        )
        torch.nn.init.xavier_uniform_(self.mode_head[1].weight)
        torch.nn.init.zeros_(self.mode_head[1].bias)
        torch.nn.init.zeros_(self.mode_head[3].weight)
        torch.nn.init.zeros_(self.mode_head[3].bias)

    def fix_state_dict(
        self: Any, state_dict: dict[str, Any], model_config: Any
    ) -> dict[str, Any]:
        fixed = original_fix_state_dict(self, state_dict, model_config)
        for key, value in self.model.mode_head.state_dict().items():
            fixed.setdefault(f"mode_head.{key}", value.detach().clone())
        return fixed

    def peft_defaults(self: Any) -> dict[str, Any]:
        defaults = original_peft_defaults(self)
        if defaults is None:
            raise RuntimeError("PI0.5 does not expose PEFT target defaults")
        return configure_pi05_mode_head_peft_defaults(defaults)

    PI05Pytorch.__init__ = model_init
    PI05Pytorch._parcel_mode_head_installed = True
    PI05Pytorch._parcel_mode_head_pooling = pooling
    PI05Policy._fix_pytorch_state_dict_keys = fix_state_dict
    PI05Policy._get_default_peft_targets = peft_defaults
